# Generated by Django 5.0.3 on 2024-08-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Authentication',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('qualifications', models.CharField(max_length=200)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Authentication',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('parrot', 'Parrot'), ('bird', 'Bird'), ('reptile', 'Reptile'), ('other', 'Other')], max_length=16)),
            ],
        ),
    ]
